name: My First Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, DevOps world!"

      - name: Show current date
        run: date

      - name: Show runner OS info
        run: uname -a
